import type { Metadata } from "next";
import "./globals.css";
import * as React from "react";
import { StyledRoot } from "./util/StyledRoot";
import { NavAndDrawerProvider, UserDataProvider } from "./util/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"1"}>
        <NavAndDrawerProvider>
          <UserDataProvider>
            <StyledRoot>{children}</StyledRoot>
          </UserDataProvider>
        </NavAndDrawerProvider>
      </body>
    </html>
  );
}
