import type { Metadata } from "next";
import "./globals.css";
import * as React from "react";
import { StyledRoot } from "./util/StyledRoot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"1"}>
        <StyledRoot>{children}</StyledRoot>
      </body>
    </html>
  );
}
